-- 1. PostGIS 확장 활성화 (필수: 가장 먼저 실행)
CREATE EXTENSION IF NOT EXISTS postgis;

-- ==========================================
-- 2. real_estate_sales (실거래가) 테이블 및 인덱스
-- ==========================================
CREATE TABLE real_estate_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name VARCHAR(200),
    deal_amount BIGINT NOT NULL,
    exclusive_area NUMERIC(7,2) NOT NULL,
    floor_no INTEGER,
    deal_ym CHAR(6) NOT NULL,
    lawd_cd VARCHAR(10) NOT NULL,
    jibun VARCHAR(200),
    geom geometry(Point, 4326) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 공간 인덱스 및 조회 최적화 인덱스 생성
CREATE INDEX gist_res_geom ON real_estate_sales USING GiST(geom);
CREATE INDEX gist_res_geog ON real_estate_sales USING GiST((geom::geography)); -- 함수형 공간 인덱스
CREATE INDEX idx_res_lawd_ym ON real_estate_sales(lawd_cd, deal_ym);


-- ==========================================
-- 3. poi (상권/인프라) 테이블 및 인덱스
-- ==========================================
CREATE TABLE poi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(30) NOT NULL,
    category_group VARCHAR(20) NOT NULL,
    address VARCHAR(255),
    geom geometry(Point, 4326) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 공간 인덱스 및 카테고리 인덱스 생성
CREATE INDEX gist_poi_geom ON poi USING GiST(geom);
CREATE INDEX gist_poi_geog ON poi USING GiST((geom::geography)); -- 함수형 공간 인덱스
CREATE INDEX idx_poi_category ON poi(category);


-- ==========================================
-- 4. region_summary (사전 집계 요약 - 줌아웃 ≤ 14)
-- ==========================================
CREATE TABLE region_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_cd VARCHAR(5) NOT NULL UNIQUE,
    region_name VARCHAR(100) NOT NULL,
    geom geometry(Point, 4326) NOT NULL,
    center_lon DOUBLE PRECISION NOT NULL,
    center_lat DOUBLE PRECISION NOT NULL,
    deal_count INTEGER NOT NULL DEFAULT 0,
    avg_amount BIGINT,
    max_amount BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 공간 인덱스 및 식별자 인덱스 생성
CREATE INDEX gist_region_geom ON region_summary USING GiST(geom);

-- LOC-01 ENV_PENALTY 서울 판정용 행정경계 테이블 (AGENTS.md §5)
-- 서울특별시 경계 MultiPolygon 1행을 두고 ST_Contains 로 좌표의 서울(법정동 11*) 여부를 판정한다.
-- spatialDataSource(PostGIS)에서 실행.

CREATE TABLE IF NOT EXISTS seoul_boundary (
    geom geometry(MultiPolygon, 4326) NOT NULL
);

CREATE INDEX IF NOT EXISTS gist_seoul_geom ON seoul_boundary USING GIST (geom);

-- 시드
--   운영: 서울시 행정경계 GeoJSON(법정동 11* 합집합)을 MultiPolygon 1행으로 적재한다.
--   개발/통합테스트: 아래 단순화 사각형으로 대체(서울 대략 경계 lng 126.76~127.18, lat 37.41~37.70).
--   ST_MakeEnvelope 는 POLYGON 을 반환하므로 ST_Multi 로 컬럼 typmod(MultiPolygon)에 맞춘다.
INSERT INTO seoul_boundary (geom)
SELECT ST_Multi(ST_SetSRID(ST_MakeEnvelope(126.76, 37.41, 127.18, 37.70, 4326), 4326))
WHERE NOT EXISTS (SELECT 1 FROM seoul_boundary);
