-- 1. PostGIS 확장 활성화 (필수: 가장 먼저 실행)
CREATE EXTENSION IF NOT EXISTS postgis;

-- ==========================================
-- 2. real_estate_sales (실거래가) 테이블 및 인덱스
-- ==========================================
CREATE TABLE real_estate_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name VARCHAR(200),
    deal_amount BIGINT,                          -- 매매가(만원). 전월세는 NULL (§8.1.1)
    deal_type VARCHAR(10) NOT NULL,              -- SALE | JEONSE | WOLSE
    property_type VARCHAR(20) NOT NULL,          -- APT | OFFICETEL | ROW_HOUSE (원룸 제외 3종)
    deposit BIGINT,                              -- 보증금(만원). 전세·월세
    monthly_rent INTEGER,                        -- 월세(만원). 월세만
    build_year SMALLINT,                         -- 건축년도
    exclusive_area NUMERIC(7,2) NOT NULL,
    floor_no INTEGER,
    deal_ym CHAR(6) NOT NULL,
    lawd_cd VARCHAR(10) NOT NULL,
    jibun VARCHAR(200),
    geom geometry(Point, 4326) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 공간 인덱스 및 조회 최적화 인덱스 생성
CREATE INDEX gist_res_geom ON real_estate_sales USING GiST(geom);
CREATE INDEX gist_res_geog ON real_estate_sales USING GiST((geom::geography)); -- 함수형 공간 인덱스
CREATE INDEX idx_res_lawd_ym ON real_estate_sales(lawd_cd, deal_ym);
CREATE INDEX idx_res_filter ON real_estate_sales(deal_type, property_type); -- §8.1.1 검색 필터


-- ==========================================
-- 3. poi (상권/인프라) 테이블 및 인덱스
-- ==========================================
CREATE TABLE poi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(30) NOT NULL,
    category_group VARCHAR(20) NOT NULL,
    address VARCHAR(255),
    geom geometry(Point, 4326) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 공간 인덱스 및 카테고리 인덱스 생성
CREATE INDEX gist_poi_geom ON poi USING GiST(geom);
CREATE INDEX gist_poi_geog ON poi USING GiST((geom::geography)); -- 함수형 공간 인덱스
CREATE INDEX idx_poi_category ON poi(category);


-- ==========================================
-- 4. region_summary (사전 집계 요약 - 줌아웃 ≤ 14)
-- ==========================================
CREATE TABLE region_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_cd VARCHAR(5) NOT NULL UNIQUE,
    region_name VARCHAR(100) NOT NULL,
    geom geometry(Point, 4326) NOT NULL,
    center_lon DOUBLE PRECISION NOT NULL,
    center_lat DOUBLE PRECISION NOT NULL,
    deal_count INTEGER NOT NULL DEFAULT 0,
    avg_amount BIGINT,
    max_amount BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 공간 인덱스 및 식별자 인덱스 생성
CREATE INDEX gist_region_geom ON region_summary USING GiST(geom);

-- ==========================================
-- 5. property_score (매물별 입지 점수 사전계산, AGENTS.md §5.1)
--    매물 1:1. 가중치 미적용 4그룹 base 를 배치(PropertyScoreBatch)가 upsert.
--    MAP-01 DETAIL 이 LEFT JOIN 으로 마커에 base 포함(미계산 매물은 0).
-- ==========================================
CREATE TABLE property_score (
    property_id      BIGINT PRIMARY KEY REFERENCES real_estate_sales(id) ON DELETE CASCADE,
    transit_base     DOUBLE PRECISION NOT NULL DEFAULT 0,
    education_base   DOUBLE PRECISION NOT NULL DEFAULT 0,
    commerce_base    DOUBLE PRECISION NOT NULL DEFAULT 0,
    convenience_base DOUBLE PRECISION NOT NULL DEFAULT 0,
    computed_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==========================================
-- 6. building_price_history (실거래가 추이 차트용, 좌표·지오코딩 없음)
--    국토부 월별 실거래가를 단지(building_name+lawd_cd)·거래유형·월 단위로 평균 집계.
--    대표가(avg_amount) = SALE:매매가 / JEONSE:보증금 / WOLSE:월세 평균. 마커·SUMMARY 영향 0.
-- ==========================================
CREATE TABLE building_price_history (
    building_name VARCHAR(200) NOT NULL,
    lawd_cd       VARCHAR(10)  NOT NULL,
    deal_type     VARCHAR(10)  NOT NULL,   -- SALE | JEONSE | WOLSE
    deal_ym       CHAR(6)      NOT NULL,
    avg_amount    BIGINT       NOT NULL,   -- 그 달 대표가 평균(만원)
    deal_count    INTEGER      NOT NULL,
    PRIMARY KEY (building_name, lawd_cd, deal_type, deal_ym)
);
